Lesson6
MobileProto16/Mobile-Proto-16 pull request #24
Opened 2016-09-12 16:01 UTC by shrutiyer

2016-09-12 16:15 UTC, davidabrahams commented
Yayyyyyy. Will review eventually. <3

2016-09-16 18:23 UTC, davidabrahams commented on lesson6/README.md
> +Apps like FB Messenger or Snapchat would go through many periodic Usability Testing. It is important to make sure that your app remains sleek and intuitive while adding new features or editing existi
grammar

2016-09-16 18:25 UTC, davidabrahams commented on lesson6/README.md
> +      * Try devices of different screen sizes.
Try different hardware. Try different OSs.

2016-09-16 18:25 UTC, davidabrahams commented on lesson6/README.md
> +While writing the XML files for your app, you might have noticed there are numerous ways to layout and display the content. [This](https://developer.android.com/guide/topics/ui/declaring-layout.html)
Maybe make this reading part of HW

2016-09-16 18:54 UTC, davidabrahams commented on lesson6/README.md
> +Whenever you need to provide the users with a prominent enough message, use pop-up messages. Most of the time, the user doesn't have to respond to the message. Also, the message disappears after a sh
Maybe detail how to do this? (What does a non-intrusive non-blocking pop up look like?)

2016-09-16 18:54 UTC, davidabrahams commented on lesson6/README.md
> +Asking question while looking at an app can be incredibly helpful while trying to design something. Once you have an idea what your app is going to be about, make a first rought draft. Concentrate on
questions

2016-09-16 18:55 UTC, davidabrahams commented on lesson6/README.md
> +  2. Observe and ask questions about the design intention. The design principles will help you here. Write up the questions and the corresponding findings?
What design principles?

2016-09-16 18:55 UTC, davidabrahams commented on lesson6/README.md
> +  3. You might have thoughts about a different layout. Prototype on paper. Include your prototype's picture (and its revisions) in your write-up. You could also use one of the programs (like Fluid UI
A different layout for the FB app?

2016-09-16 18:55 UTC, davidabrahams commented on lesson6/README.md
> +  1. Download Facebook app on an Android phone (if you don't have access to either a Facebook account or an Android phone, let the teaching team know)
Should we let them choose what app (FB, twitter, instagram, etc)? Maybe ask them to do 2-3 and compare them?

2016-09-16 18:56 UTC, davidabrahams commented on lesson6/README.md
> +  4. (Optional) Recreate your layout(s) in Android Studio by writing XML file(s) for them.
Like, make their previous apps pretty? I think this should be mandatory...

2016-09-16 18:57 UTC, davidabrahams requested changes
Maybe you should make a [HW] tag for the parts they have to do, so they know what "getting through the README" means.

2016-09-16 18:57 UTC, davidabrahams commented on lesson6/README.md
> +Fill out [this survey](https://goo.gl/forms/LLUhDfZzBkkqawtp1) after you finish the HW
Assuming they have to change their code, we should ask for a link to the repo where their code is (unless we just assume its in their class repo)

2016-09-16 23:09 UTC, nmohamed requested changes
do this

2016-09-16 23:10 UTC, nmohamed commented on lesson6/README.md
> +
maybe preface this with a short intro to what this lesson is about? also specify the due date of it above

2016-09-16 23:12 UTC, nmohamed commented on lesson6/README.md
> +  4. How does the color scheme fit the overall feel?
how about "how easy are certain buttons to press? do you press those buttons often?"

2016-09-16 23:12 UTC, nmohamed commented on lesson6/README.md
> +Draw the screens on pieces of paper (or use one of the many online programs like fluidui). Test these mockups on your friends. It is recommended that you let your friends first explore the mockups wi
paint, photoshop, whiteboards, your approved medium of art

2016-09-16 23:13 UTC, nmohamed commented on lesson6/README.md
> +Next step is to integrate whatever feedback you received from the User Testing into your app design. At this stage, you can also decide on the color scheme of the app, logo, name etc. You could do cy
➔

2016-09-16 23:31 UTC, nmohamed commented on lesson6/README.md
> +Apps like FB Messenger or Snapchat would go through many periodic Usability Testing. It is important to make sure that your app remains sleek and intuitive while adding new features or editing existi
spell out Facebook
why is Usability Testing capitalized? grammar for that sentence

2016-09-16 23:32 UTC, nmohamed commented on lesson6/README.md
> +Once you have a Minimum Viable Product (MVP) of your app, test again. But this time, it is a little different.
*test it again.
Don't really need the "But this time, it is a little different."
Maybe mention trying to test it after adding little things

2016-09-16 23:41 UTC, nmohamed commented on lesson6/README.md
> +  2. Observe and ask questions about the design intention. The design principles will help you here. Write up the questions and the corresponding findings?
remove question mark

2016-09-16 23:42 UTC, nmohamed commented on lesson6/README.md
> +
also, it's a bit confusing reading through this. when i started it sounds like you're giving instructions to me, so it seemed like the entire thing is homework

2016-09-16 23:42 UTC, nmohamed requested changes
hi

2016-09-16 23:55 UTC, nmohamed approved these changes

2016-09-18 15:53 UTC, billmwong commented on lesson6/README.md
> +Open up any app on your phone. It could be very simple or very complex; there's something to learn from both. While using it, ask questions. Some examples of questions could be:
Should it only be an android app? IOS apps have slightly different design principles.  Or is this guide for general design, not just android design?

2016-09-18 15:57 UTC, billmwong commented on lesson6/README.md
> +  4. (Optional) Recreate your layout(s) in Android Studio by writing XML file(s) for them.
Yeah, I feel like there has to be some sort of coding/do it yourself in android studio portion of the assignment

2016-09-18 15:57 UTC, billmwong requested changes

2016-09-18 20:21 UTC, shrutiyer commented on lesson6/README.md
> +Whenever you need to provide the users with a prominent enough message, use pop-up messages. Most of the time, the user doesn't have to respond to the message. Also, the message disappears after a sh
There is a picture in the readme that shows the non-intrusive pop-up. Do we need to show anything more than that?

2016-09-18 20:23 UTC, shrutiyer commented on lesson6/README.md
> +  1. Download Facebook app on an Android phone (if you don't have access to either a Facebook account or an Android phone, let the teaching team know)
I wanted to choose a complicated app where too many things are happening. FB has way more stuff than twitter. I haven't used Instagram

2016-09-18 20:24 UTC, shrutiyer commented on lesson6/README.md
> +  2. Observe and ask questions about the design intention. The design principles will help you here. Write up the questions and the corresponding findings?
Android design principles mentioned above

2016-09-18 20:38 UTC, shrutiyer commented on lesson6/README.md
> +  3. You might have thoughts about a different layout. Prototype on paper. Include your prototype's picture (and its revisions) in your write-up. You could also use one of the programs (like Fluid UI
yep

2016-09-18 20:38 UTC, shrutiyer commented on lesson6/README.md
> +  4. (Optional) Recreate your layout(s) in Android Studio by writing XML file(s) for them.
Made it required

2016-09-18 20:49 UTC, shrutiyer commented
Made more small changes. Comment on the new stuff.

2016-09-19 00:11 UTC, billmwong approved these changes
Approved!

2016-09-21 16:15 UTC, davidabrahams approved these changes

2016-09-21 16:15 UTC, merged